[project]
name = "pybasic"
version = "0.0.1"
description = "Background and shading correction for microscopy images"
readme = "README.md"
requires-python = ">=3.7"
license = { file = "LICENSE" }
authors = [{ name = "Sebastian Ahn" }]
keywords = [
    "microscopy",
    "imaging",
    "bio-imaging"
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Image Processing",
]
dependencies = [
    'dask',
    'distributed',
    'imagecodecs',
    'numpy',
    'pillow',
    'pint',
    'scipy',
    'scikit-image',
    'tifffile'
]

[project.optional-dependencies]
# build = ["build", "twine"]
dev = [
    "black",
    "graphviz",
    "ipywidgets",
    "jupyterlab",
    "matplotlib",
    "perfplot",
    "pytest",
    'viztracer',
]

[project.urls]
repository = "https://github.com/biomicrodev/pybasic"
laboratory = "https://jonaslab.bwh.harvard.edu"

#[project.scripts]
#pybasic = "pybasic.__main__:main"


[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"